name: Secret Value found!!
on:
  push:
  public:
jobs:
  scan:
    name: gitleaks
    runs-on: windows-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v4.2.2
     - name: Install the gitleaks
       run: wget https://github.com/zricethezav/gitleaks/releases/download/v8.24.2/gitleaks_8.24.2_windows_armv6.zip
       shell: pwsh
     
     - name: Setup NuGet.exe
       if: steps.gitleaks.outcome != 'success'
       uses: nuget/setup-nuget@v2.0.0
       with:
          nuget-version: latest
     - name: Install the dotnet
       if: steps.gitleaks.outcome != 'success'
       uses: actions/setup-dotnet@v4
       with:
          dotnet-version: '8.0.x'
     - name: Install the report tool packages
       if: steps.gitleaks.outcome != 'success'
       run: |
           nuget install "Syncfusion.Email" -source ${{ secrets.NexusFeedLink }} -ExcludeVersion
           echo " Package Installed"
           dir $GITHUB_WORKSPACE/Syncfusion.Email/lib/netcoreapp3.1
           dotnet $GITHUB_WORKSPACE/Syncfusion.Email/lib/netcoreapp3.1/GitleaksReportMail.dll ${{ secrets.CITEAMCREDENTIALS }} "$GITHUB_REF_NAME" ${{ secrets.NETWORKCREDENTIALS }} ${{ secrets.NETWORKKEY }} "$GITHUB_WORKSPACE" ${{ secrets.ORGANIZATIONNAME }}
           exit 1
